CummunityInvestmentWeb/Areas/Administrator/Controllers/MissionActivityController.cs
using CommunityInvestment.DataAccess.Repository.IRepository;
using CommunityInvestment.Models.ViewModels;
using CommunityInvestment.Models;
using Microsoft.AspNetCore.Mvc;
using CommunityInvestment.Application.Common;
using CommunityInvestment.Application.Utilities;
using System.Text.Json.Nodes;
using Microsoft.Data.SqlClient;
using System.Text.Json;
using System.Text.Json.Serialization;
using Newtonsoft.Json;
using System.Net;
using Microsoft.AspNetCore.Authorization;
using System.Data;

namespace CummunityInvestmentWeb.Areas.Administrator.Controllers
{
    [Authorize(Roles = "Admin")]
    public class MissionActivityController : Controller
    {
        public readonly IUnitOfWork _unitOfWork;
        public readonly IWebHostEnvironment webHostEnvironment;
        public MissionActivityController(IUnitOfWork unitOfWork, IWebHostEnvironment webHostEnvironment)
        {
            _unitOfWork = unitOfWork;
            this.webHostEnvironment = webHostEnvironment;
        }


        //-- Managing Missions
        public IActionResult ManageMissions()
        {
            return View();
        }

        [HttpPost]
        public IActionResult GetMissionsDataTable()
        {
            DataTableFilterVM missionsDTFilter = new DataTableFilterVM(Request);
            DataTableVM<Mission> missionsDataTable = _unitOfWork.AdminMission.GetMissionsDT(missionsDTFilter);
            return Json(missionsDataTable);
        }

        public IActionResult GetCitiesByCountry(long countryId)
        {
            var Cities = _unitOfWork.Filter.GetCitiesByCountryId(countryId);
            return Json(Cities);
        }

        [Route("Administrator/MissionActivity/AddMission")]
        [Route("Administrator/MissionActivity/EditMission/{missionId}")]
        public IActionResult GetMissionEdit(long? missionId)
        {
            ViewBag.Countries = _unitOfWork.Filter.GetAllCountry();
            ViewBag.Skills = _unitOfWork.Filter.GetAllSkills().Where(ms=>ms.DeletedAt == null && ms.Status == "1");
            ViewBag.Themes = _unitOfWork.Filter.GetAllMissionTheme().Where(theme=>theme.DeletedAt == null && theme.Status == 1);
            AdminMissionVM missionVM = new AdminMissionVM();
            if (missionId != null)
            {
                missionVM = _unitOfWork.AdminMission.GetMissionEdit((long)missionId);
                if (missionVM != null)
                    ViewBag.CountryCities = _unitOfWork.Filter.GetCitiesByCountryId(missionVM.CountryId);
                else
                    BadRequest();
            }
            return View("~/Areas/Administrator/Views/MissionActivity/MissionPage.cshtml", missionVM);
        }

        [HttpPost]
        public IActionResult UploadMissionImages()
        {
            List<IFormFile> MissionImages = Request.Form.Files.ToList();
            List<string> uniqueFileNamesList = new List<string>();
            if (MissionImages != null && MissionImages.Count > 0)
            {
                foreach (IFormFile MissionImage in MissionImages)
                {
                    string uploadsFolder = Path.Combine(webHostEnvironment.WebRootPath, "data", "Images", "Mission");
                    string uniqueFileName = GeneralUtility.UploadFile(uploadsFolder, MissionImage);
                    uniqueFileNamesList.Add(uniqueFileName);
                    //MissionImage.CopyTo(new FileStream(filePath, FileMode.Create));
                }
            };
            return Json(uniqueFileNamesList);
        }
        
        [HttpPost]
        public IActionResult UploadMissionDocuments()
        {
            List<IFormFile> MissionDocuments = Request.Form.Files.ToList();
            List<string> uniqueFileNamesList = new List<string>();
            if (MissionDocuments != null && MissionDocuments.Count > 0)
            {
                foreach (IFormFile MissionImage in MissionDocuments)
                {
                    string uploadsFolder = Path.Combine(webHostEnvironment.WebRootPath, "data", "Documents", "MissionDocs");
                    string uniqueFileName = GeneralUtility.UploadFile(uploadsFolder, MissionImage);
                    uniqueFileNamesList.Add(uniqueFileName);
                }
            };
            return Json(uniqueFileNamesList);
        }

        public IActionResult GetUploadedImages(long missionId)
        {
            List<MissionMedium> missionImages = _unitOfWork.AdminMission.GetExistingMissionImages(missionId);
            List<JsonObject> missionImagesObj = new List<JsonObject>();
            if (missionImages != null && missionImages.Count > 0)
            {
                foreach (var missionImage in missionImages)
                {
                    FileInfo missionImageInfo = GeneralUtility.GetFileInfo(webHostEnvironment.WebRootPath, missionImage.MediaPath);
                    if (missionImageInfo.Exists)
                    {
                        var newObj = new JsonObject
                        {
                            ["missionImageId"] = missionImage.MissionMediaId, 
                            ["name"] = missionImage.MediaName,
                            ["path"] = missionImage.MediaPath,
                            ["size"] = missionImageInfo.Length,
                            ["type"] = "image/"
                        };
                        missionImagesObj.Add(newObj);
                    }
                }
            }
            return Json(missionImagesObj);
        }

        public IActionResult GetUploadedDocuments(long missionId)
        {
            List<MissionDocument> missionDocuments = _unitOfWork.AdminMission.GetExistingMissionDocuments(missionId);
            List<JsonObject> missionImagesObj = new List<JsonObject>();
            if (missionDocuments != null && missionDocuments.Count > 0)
            {
                foreach (var missionDocument in missionDocuments)
                {
                    FileInfo missionDocumentInfo = GeneralUtility.GetFileInfo(webHostEnvironment.WebRootPath, missionDocument.DocumentPath);
                    if (missionDocumentInfo.Exists)
                    {
                        var newObj = new JsonObject
                        {
                            ["missionDocumentId"] = missionDocument.MissionDocumentId,
                            ["name"] = missionDocument.DocumentName,
                            ["path"] = missionDocument.DocumentPath,
                            ["size"] = missionDocumentInfo.Length,
                            ["type"] = missionDocumentInfo.Extension
                        };
                        missionImagesObj.Add(newObj);
                    }
                }
            }
            return Json(missionImagesObj);
        }

        [HttpPost]
        public IActionResult RemoveUploadedImage(long missionImageId)
        {
            MissionMedium missionImage = _unitOfWork.AdminMission.GetMissionImage(missionImageId);
            if (missionImage != null)
            {
                if (_unitOfWork.AdminMission.RemoveMissionImage(missionImage))
                {
                    _unitOfWork.Save();
                    return Ok("File Removed!");
                }
            }
            return BadRequest("File not exists or Some error!");
        }
        
        [HttpPost]
        public IActionResult RemoveUploadedDocument(long missionDocumentId)
        {
            MissionDocument missionDocument = _unitOfWork.AdminMission.GetMissionDocument(missionDocumentId);
            if (missionDocument != null)
            {
                if (_unitOfWork.AdminMission.RemoveMissionDocument(missionDocument))
                {
                    _unitOfWork.Save();
                    return Ok("File Removed!");
                }
            }
            return BadRequest("File not exists or Some error!");
        }

        [HttpPost]
        public async Task<IActionResult> SaveMissionAsync(AdminMissionVM missionData)
        {
            if(missionData.MissionType == "goal")
            {
                ModelState.Remove("StartDate");
                ModelState.Remove("EndDate");
            }
            if (ModelState.IsValid)
            {
                bool IsMissionSaved = await _unitOfWork.AdminMission.SaveMission(missionData);
                if (IsMissionSaved)
                {
                    _unitOfWork.Save();
                    TempData["SuccessMessage"] = "Mission Saved successfully!";
                    return Redirect("/Administrator/MissionActivity/ManageMissions");
                }
                TempData["ErrorMessageTitle"] = ErrorMessages.SomethingWentWrongTitle;
                TempData["ErrorMessage"] = ErrorMessages.SomethingWentWrongMessage;
            }
            return View("~/Areas/Administrator/Views/MissionActivity/MissionPage.cshtml", missionData);
        }

        public IActionResult RemoveMission(long missionId)
        {
            if (_unitOfWork.AdminMission.RemoveMission(missionId))
            {
                _unitOfWork.Save();
                return Ok("Mission Removed Successfully!");
            }
            return BadRequest();
        }

        //-- Manage Mission Themes
        public IActionResult MissionThemes()
        {
            return View();
        }

        [HttpPost]
        public IActionResult GetMissionThemesDataTable()
        {
            DataTableFilterVM missionThemesDTFilter = new DataTableFilterVM(Request);
            DataTableVM<MissionTheme> missionThemesDataTable = _unitOfWork.AdminMission.GetMissionThemesDT(missionThemesDTFilter);
            return Json(missionThemesDataTable);
        }

        public IActionResult GetMissionThemeEdit(long missionThemeId)
        {
            var missionTheme = _unitOfWork.Filter.GetMissionThemeById(missionThemeId);
            if(missionTheme == null)
                return NotFound();
            return Json(missionTheme);
        }

CummunityInvestmentWeb/Areas/Administrator/Views/MissionActivity/ManageMissions.cshtml
@{
    ViewData["Title"] = "Manage Missions";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@section Styles{
    @*<link rel="stylesheet" href=@Url.Content("~/css/AdminActivity/ManageMissions.css") asp-append-version="true" />*@
}

<div class="mission-manage-container px-3">
    <div class="title-underline-wrapper mb-4">
        <h4 class="title pb-3">Mission</h4>
    </div>
    <div class="row mb-4">
        <div class="col-8 col-lg-6">
            <input class="form-control input input-search" id="table-search" placeholder="Search Mission" />
        </div>
        <div class="col-4 col-lg-6 text-end">
            <a class="btn primary-btn" id="admin-add-mission-btn" asp-controller="MissionActivity" asp-action="AddMission">
                <i class="bi bi-plus-lg rg-icon"></i>
                <span>Add</span>
            </a>
        </div>
    </div>

    <!-- CMS Pages table -->
    <div class="w-100">
        <div class="table-responsive admin-table-wrapper">
            <table class="table align-middle admin-table w-100 border" id="missions-table">
                <thead class="table-light">
                    <tr>
                        <th scope="col">Mission Title</th>
                        <th scope="col">Mission Type</th>
                        <th scope="col">Start Date</th>
                        <th scope="col">End Date</th>
                        <th scope="col">Action</th>
                    </tr>
                </thead>
                <tbody></tbody>
            </table>
        </div>
    </div>

    <partial name="_RemoveItemConfirmModal"></partial>
</div>

@section Scripts {
    <script src="~/js/AdminActivity/MissionActivity/ManageMissions.js" asp-append-version="true"></script>
}

CummunityInvestmentWeb/Areas/Administrator/Views/MissionActivity/MissionApplications.cshtml
@{
    ViewData["Title"] = "Mission Applications";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@section Styles{
    @*<link rel="stylesheet" href=@Url.Content("~/css/AdminActivity/MissionApplications.css") asp-append-version="true" />*@
}

<div class="mission-applications-container px-3">
    <div class="title-underline-wrapper mb-4">
        <h4 class="title pb-3">Mission Applications</h4>
    </div>
    <div class="row mb-4">
        <div class="col-8 col-lg-6">
            <input class="form-control input input-search" id="table-search" placeholder="Search for Mission Applications" />
        </div>
    </div>

    <!-- Mission Applications table -->
    <div class="w-100">
        <div class="table-responsive admin-table-wrapper">
            <table class="table align-middle admin-table w-100 border" id="mission-applications-table">
                <thead class="table-light">
                    <tr>
                        <th scope="col">Mission Title</th>
                        <th scope="col">Mission Id</th>
                        <th scope="col">User Id</th>
                        <th scope="col">User Name</th>
                        <th scope="col">Applied Date</th>
                        <th scope="col">Action</th>
                    </tr>
                </thead>
                <tbody></tbody>
            </table>
        </div>
    </div>

    <partial name="_RemoveItemConfirmModal"></partial>
</div>

@section Scripts {
    <script src="~/js/AdminActivity/MissionActivity/MissionApplications.js" asp-append-version="true"></script>
}

CummunityInvestmentWeb/Areas/Administrator/Views/MissionActivity/MissionSkills.cshtml
@model AdminMissionSkillVM
@{
    ViewData["Title"] = "Mission Skills";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@functions {
    public string IsValidField(string Key, ModelStateDictionary modelState)
    {
        return modelState.TryGetValue(Key, out var entry) && entry.Errors.Count > 0 ? "is-invalid" : "";
    }
}

@section Styles{
    @*<link rel="stylesheet" href=@Url.Content("~/css/AdminActivity/MissionSkills.css") asp-append-version="true" />*@
}

<div class="mission-skills-container px-3">
    <div class="title-underline-wrapper mb-4">
        <h4 class="title pb-3">Mission SKill</h4>
    </div>
    <div class="row mb-4">
        <div class="col-8 col-lg-6">
            <input class="form-control input input-search" id="table-search" placeholder="Search Skill" />
        </div>
        <div class="col-4 col-lg-6 text-end">
            <a class="btn primary-btn" id="admin-add-missionSkill-btn" data-bs-toggle="modal" data-bs-target="#mission-skill-modal">
                <i class="bi bi-plus-lg rg-icon"></i>
                <span>Add</span>
            </a>
        </div>
    </div>

    <!-- Mission Skills table -->
    <div class="w-100">
        <div class="table-responsive admin-table-wrapper">
            <table class="table align-middle admin-table w-100 border" id="mission-skills-table">
                <thead class="table-light">
                    <tr>
                        <th scope="col">Mission Skill Name</th>
                        <th scope="col">Status</th>
                        <th scope="col">Action</th>
                    </tr>
                </thead>
                <tbody></tbody>
            </table>
        </div>
    </div>

    <div class="modal fade" id="mission-skill-modal" data-bs-backdrop="static" tabindex="-1" aria-labelledby="missionSkillModal">
        <div class="modal-dialog modal-dialog-centered modal-fullscreen-xxl-down" id="admin-mission-skill-modal-dialog">
            <div class="modal-content">
                <form id="mission-skill-form">
                    <div class="modal-header border-bottom-0">
                        <h1 class="modal-title fs-5" id="">Add Skill</h1>
                        <button type="button" class="btn-close cancel-action-btn" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body" id="mission-skill-modalBody">
                        <input asp-for="SkillId" hidden />
                        <div class="input-container mb-3">
                            <label asp-for="SkillName" class="form-label"></label>
                            <input asp-for="SkillName" class="form-control input @IsValidField("SkillName", ViewData.ModelState)" placeholder="Enter Skill Name">
                            <span asp-validation-for="SkillName" class="invalid-feedback"></span>
                        </div>
                        <div class="input-container mb-3">
                            <label asp-for="Status" class="form-label"></label>
                            <select asp-for="Status" class="form-select input @IsValidField("Status", ViewData.ModelState)">
                                <option value="1">Active</option>
                                <option value="0">InActive</option>
                            </select>
                            <span asp-validation-for="Status" class="invalid-feedback"></span>
                        </div>
                    </div>
                    <div class="modal-footer border-0">
                        <button type="button" class="btn secondary-btn cancel-action-btn" data-bs-dismiss="modal">Cancel</button>
                        <button type="submit" class="btn primary-btn" id="save-missionSkill-btn">
                            <span class="btn-loader spinner-border spinner-border-sm d-none" role="status" aria-hidden="true"></span>
                            <span class="btn-content">Save</span>
                            <span class="btn-loader d-none">Please wait...</span>
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <partial name="_RemoveItemConfirmModal"></partial>
</div>

@section Scripts {
    <script src="~/js/AdminActivity/MissionActivity/MissionSkills.js" asp-append-version="true"></script>
}

CummunityInvestmentWeb/Areas/Administrator/Views/MissionActivity/MissionThemes.cshtml
@model AdminMissionThemeVM

@{
    ViewData["Title"] = "Mission Themes";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@functions {
    public string IsValidField(string Key, ModelStateDictionary modelState)
    {
        return modelState.TryGetValue(Key, out var entry) && entry.Errors.Count > 0 ? "is-invalid" : "";
    }
}

@section Styles{
    @*<link rel="stylesheet" href=@Url.Content("~/css/AdminActivity/MissionThemes.css") asp-append-version="true" />*@
}

<div class="mission-themes-container px-3">
    <div class="title-underline-wrapper mb-4">
        <h4 class="title pb-3">Mission Theme</h4>
    </div>
    <div class="row mb-4">
        <div class="col-8 col-lg-6">
            <input class="form-control input input-search" id="table-search" placeholder="Search Mission Theme" />
        </div>
        <div class="col-4 col-lg-6 text-end">
            <a class="btn primary-btn" id="admin-add-missionTheme-btn" data-bs-toggle="modal" data-bs-target="#mission-theme-modal">
                <i class="bi bi-plus-lg rg-icon"></i>
                <span>Add</span>
            </a>
        </div>
    </div>

    <!-- Mission Themes table -->
    <div class="w-100">
        <div class="table-responsive admin-table-wrapper">
            <table class="table align-middle admin-table w-100 border" id="mission-themes-table">
                <thead class="table-light">
                    <tr>
                        <th scope="col">Mission Theme Title</th>
                        <th scope="col">Status</th>
                        <th scope="col">Action</th>
                    </tr>
                </thead>
                <tbody></tbody>
            </table>
        </div>
    </div>

    <div class="modal fade" id="mission-theme-modal" data-bs-backdrop="static" tabindex="-1" aria-labelledby="missionThemeModal">
        <div class="modal-dialog modal-dialog-centered modal-fullscreen-xxl-down" id="admin-mission-theme-modal-dialog">
            <div class="modal-content">
                <form id="mission-theme-form">
                    <div class="modal-header border-bottom-0">
                        <h1 class="modal-title fs-5" id="">Add Mission Theme</h1>
                        <button type="button" class="btn-close cancel-action-btn" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body" id="mission-theme-modalBody">
                        <input asp-for="MissionThemeId" hidden />
                        <div class="input-container mb-3">
                            <label asp-for="ThemeTitle" class="form-label"></label>
                            <input asp-for="ThemeTitle" class="form-control input @IsValidField("ThemeTitle", ViewData.ModelState)" placeholder="Enter Mission Theme Title">
                            <span asp-validation-for="ThemeTitle" class="invalid-feedback"></span>
                        </div>
                        <div class="input-container mb-3">
                            <label asp-for="Status" class="form-label"></label>
                            <select asp-for="Status" class="form-select input @IsValidField("Status", ViewData.ModelState)">
                                <option value="1">Active</option>
                                <option value="0">InActive</option>
                            </select>
                            <span asp-validation-for="Status" class="invalid-feedback"></span>
                        </div>
                    </div>
                    <div class="modal-footer border-0">
                        <button type="button" class="btn secondary-btn cancel-action-btn" data-bs-dismiss="modal">Cancel</button>
                        <button type="submit" class="btn primary-btn" id="save-missionTheme-btn">
                            <span class="btn-loader spinner-border spinner-border-sm d-none" role="status" aria-hidden="true"></span>
                            <span class="btn-content">Save</span>
                            <span class="btn-loader d-none">Please wait...</span>
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <partial name="_RemoveItemConfirmModal"></partial>
</div>

@section Scripts {
    <script src="~/js/AdminActivity/MissionActivity/MissionThemes.js" asp-append-version="true"></script>
}

CummunityInvestmentWeb/Areas/Administrator/Views/MissionActivity/Stories.cshtml
@{
    ViewData["Title"] = "Stories";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@section Styles{
    <link rel="stylesheet" href="@Url.Content("~/css/VolunteerStory/StoryDetail.css")" asp-append-version="true" />
    <link rel="stylesheet" href=@Url.Content("~/css/AdminActivity/MissionActivity/Stories.css") asp-append-version="true" />
}

<div class="stories-container px-3">
    <div class="title-underline-wrapper mb-4">
        <h4 class="title pb-3">Story</h4>
    </div>
    <div class="row mb-4">
        <div class="col-8 col-lg-6">
            <input class="form-control input input-search" id="table-search" placeholder="Search by Story or Mission" />
        </div>
    </div>

    <!-- Story table -->
    <div class="w-100">
        <div class="admin-table-wrapper">
            <table class="table align-middle admin-table w-100 border" id="stories-table">
                <thead class="table-light">
                    <tr>
                        <th scope="col">Story Title</th>
                        <th scope="col">Full Name</th>
                        <th scope="col">Mission Title</th>
                        <th scope="col">Action</th>
                    </tr>
                </thead>
                <tbody></tbody>
            </table>
        </div>
    </div>

    <div class="modal fade" id="admin-story-detail-modal" tabindex="-1" aria-labelledby="storyDetail">
        <div class="modal-dialog modal-dialog-centered modal-xl modal-fullscreen-xxl-down" id="admin-story-detail-modal-dialog">
            <div class="modal-content">
                <div class="modal-header border-bottom-0">
                    <h1 class="modal-title fs-5" id="">Story Details</h1>
                    <button type="button" class="btn-close cancel-action-btn" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body" id="admin-story-detail-modalBody">
                </div>
            </div>
        </div>
    </div>

    <partial name="_RemoveItemConfirmModal"></partial>
</div>

@section Scripts {
    <script src="~/js/AdminActivity/MissionActivity/Stories.js" asp-append-version="true"></script>
}