CummunityInvestmentWeb/Areas/Administrator/Controllers/AdminActivityController.cs
using Microsoft.AspNetCore.Mvc;
using CommunityInvestment.Models;
using CommunityInvestment.DataAccess.Repository.IRepository;
using System.Data;
using CommunityInvestment.Models.ViewModels;
using CommunityInvestment.Application.Common;
using CommunityInvestment.Application.Utilities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using System.Security.Claims;

namespace CummunityInvestmentWeb.Areas.Administrator.Controllers
{
    [Authorize(Roles = "Admin")]
    public class AdminActivityController : Controller
    {
        public readonly IUnitOfWork _unitOfWork;
        public readonly IWebHostEnvironment webHostEnvironment;
        public AdminActivityController(IUnitOfWork unitOfWork, IWebHostEnvironment webHostEnvironment)
        {
            _unitOfWork = unitOfWork;
            this.webHostEnvironment = webHostEnvironment;
        }

        //--- Admin Profile and Change password
        [HttpPost]
        public IActionResult SaveProfile(AdminProfileVM adminProfileData)
        {
            long adminId = GeneralUtility.GetClaimIdentifier(User);
            if (adminId == 0)
                return BadRequest();
            ModelState.Remove("Password");
            if (!ModelState.IsValid)
                return ValidationProblem(ModelState);

            // Uploading New Admin Avatar to Server
            string oldAdminAvatarPath = adminProfileData.AdminAvatar;
            if (adminProfileData.NewAdminAvatar != null)
            {
                string path = "/data/Images/AdminAvatar/";
                string uploadsFolder = Path.Combine(webHostEnvironment.WebRootPath, "data", "Images", "AdminAvatar");
                string uploadedAvatarPath = GeneralUtility.UploadFile(uploadsFolder, adminProfileData.NewAdminAvatar, path);
                adminProfileData.AdminAvatar = uploadedAvatarPath;
            };
            // Add or Update User
            adminProfileData.AdminId = adminId;
            Admin updatedAdmin = _unitOfWork.Admin.AddOrUpdateAdmin(adminProfileData);
            if (updatedAdmin != null)
            {
                _unitOfWork.Save();
                // Delete old user avatar if exists
                if (adminProfileData.NewAdminAvatar != null && !string.IsNullOrEmpty(oldAdminAvatarPath))
                {
                    FileInfo storyImageInfo = GeneralUtility.GetFileInfo(webHostEnvironment.WebRootPath, oldAdminAvatarPath);
                    if (storyImageInfo.Exists)
                        storyImageInfo.Delete();
                }
                // Create a new identity with the updated claims
                var newIdentity = (ClaimsIdentity)User.Identity;
                newIdentity.RemoveClaim(User.FindFirst(ClaimTypes.Name)); // Remove the current Name claim
                newIdentity.AddClaim(new Claim(ClaimTypes.Name, updatedAdmin.FirstName + " " + updatedAdmin.LastName)); // Add the new Name claim
                newIdentity.RemoveClaim(User.FindFirst("FirstName"));
                newIdentity.AddClaim(new Claim("FirstName", updatedAdmin.FirstName ?? ""));
                newIdentity.RemoveClaim(User.FindFirst("LastName"));
                newIdentity.AddClaim(new Claim("LastName", updatedAdmin.LastName ?? ""));
                newIdentity.RemoveClaim(User.FindFirst("avatar_url"));
                newIdentity.AddClaim(new Claim("avatar_url", updatedAdmin.Avatar ?? "/assets/user-profile-avatar.svg"));
                newIdentity.RemoveClaim(User.FindFirst("avatar_url"));
                newIdentity.AddClaim(new Claim("avatar_url", updatedAdmin.Avatar ?? "/assets/user-profile-avatar.svg"));
                // Create a new principal with the updated identity
                var newPrincipal = new ClaimsPrincipal(newIdentity);
                // Update the current user session with the new principal
                HttpContext.User = newPrincipal;
                HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, newPrincipal);

                string returnMessage = "Profile Saved!";
                return Ok(returnMessage);
            }
            return BadRequest("Something went wrong!");

        }

        [HttpPost]
        public IActionResult ChangePassword(ChangePasswordVM changePassword)
        {
            if (changePassword.NewPassword.Equals(changePassword.OldPassword))
                return ValidationProblem("New and Old password Same");
            if (!changePassword.NewPassword.Equals(changePassword.ConfirmPassword))
                return ValidationProblem("NewPassword and ConfirmPassword not Matched!");
            long adminId = GeneralUtility.GetClaimIdentifier(User);
            if (adminId != 0)
            {
                bool IsOldPasswordValid = _unitOfWork.Admin.CheckOldPassword(adminId, changePassword.OldPassword);
                if (!IsOldPasswordValid)
                    return ValidationProblem("Invalid OldPassword");
                bool IsPasswordUpdated = _unitOfWork.Admin.UpdatePassword(adminId, changePassword.NewPassword);
                if (IsPasswordUpdated)
                {
                    _unitOfWork.Save();
                    return Ok("Password Updated!");
                }
            }
            return BadRequest("401");
        }


        //--- Manage Users
        public IActionResult ManageUsers()
        {
            ViewBag.Countries = _unitOfWork.Filter.GetAllCountry();
            return View();
        }

        [HttpPost]
        public IActionResult GetUsersDataTable()
        {
            DataTableFilterVM usersDTFilter = new DataTableFilterVM(Request);
            DataTableVM<User> userDataTable = _unitOfWork.Admin.GetUsersDT(usersDTFilter);
            return Json(userDataTable);
        }

        public IActionResult GetUserEdit(long? userId)
        {
            ViewBag.Countries = _unitOfWork.Filter.GetAllCountry();
            AdminUserManageVM userProfileModal = new AdminUserManageVM();
            if (userId != null)
            {
                userProfileModal = _unitOfWork.Admin.GetUserEdit((long)userId);
                ViewBag.CountryCities = _unitOfWork.Filter.GetCitiesByCountryId(userProfileModal.CountryId);
            }
            return PartialView("~/Areas/Administrator/Views/Shared/_AddOrUpdateUserModal.cshtml", userProfileModal);
        }

        [HttpPost]
        public IActionResult AddOrUpdateUser([FromForm] AdminUserManageVM adminUserManageObj)
        {
            if (adminUserManageObj.UserId == null)
            {
                User user = _unitOfWork.User.GetByEmail(adminUserManageObj.Email);
                if (user != null)
                    ModelState.AddModelError("Email", UserMessages.EmailRegistered);
            }
            if (adminUserManageObj.UserId != null)
            {
                ModelState.Remove("Password");
                ModelState.Remove("ConfirmPassword");
            }
            if (!ModelState.IsValid)
                return ValidationProblem(ModelState);

            // Uploading New User Avatar to Server
            string oldUserAvatarPath = adminUserManageObj.Avatar;
            if (adminUserManageObj.NewUserAvatar != null)
            {
                string path = "/data/Images/UserAvatar/";
                string uploadsFolder = Path.Combine(webHostEnvironment.WebRootPath, "data", "Images", "UserAvatar");
                string uploadedAvatarPath = GeneralUtility.UploadFile(uploadsFolder, adminUserManageObj.NewUserAvatar, path);
                adminUserManageObj.Avatar = uploadedAvatarPath;
            };
            // Add or Update User
            string IsUserAddedOrUpdated = _unitOfWork.Admin.AddOrUpdateUser(adminUserManageObj);
            if (IsUserAddedOrUpdated != null)
            {
                _unitOfWork.Save();
                // Delete old user avatar if exists
                if (adminUserManageObj.NewUserAvatar != null && !string.IsNullOrEmpty(oldUserAvatarPath))
                {
                    FileInfo storyImageInfo = GeneralUtility.GetFileInfo(webHostEnvironment.WebRootPath, oldUserAvatarPath);
                    if (storyImageInfo.Exists)
                        storyImageInfo.Delete();
                }
                string returnMessage = IsUserAddedOrUpdated;
                return Ok(returnMessage);
            }
            return BadRequest("Something went wrong!");
        }

        public IActionResult RemoveUser(long userId)
        {
            bool IsUserRemoved = _unitOfWork.Admin.RemoveUser(userId);
            if (IsUserRemoved)
            {
                _unitOfWork.Save();
                return Ok("User Removed!");
            }
            return BadRequest();
        }


        //--- Manage CMS Pages
        public IActionResult ManageCMSPages()
        {
            return View();
        }
        public IActionResult GetCMSDataTable()
        {
            DataTableFilterVM cmsDTFilter = new DataTableFilterVM(Request);
            DataTableVM<CmsPage> cmsDataTable = _unitOfWork.Admin.GetCMS_DT(cmsDTFilter);
            return Json(cmsDataTable);
        }

        public IActionResult RemoveCMSPage(long cmsPageId)
        {
            bool IsCMSPageRemoved = _unitOfWork.Admin.RemoveCMSPage(cmsPageId);
            if (IsCMSPageRemoved)
            {
                _unitOfWork.Save();
                return Ok("CMS Page Removed Successfully!");
            }
            return BadRequest();
        }

        public IActionResult AddCMSPage()
        {
            return View("~/Areas/Administrator/Views/AdminActivity/CMSPage.cshtml");
        }

        [Route("Administrator/AdminActivity/EditCMSPage/{cmsPageId}")]
        public IActionResult EditCMSPage(long cmsPageId)
        {
            AdminCmsPageVM cmsPage = _unitOfWork.Admin.GetCMSPageById(cmsPageId);
            if (cmsPage != null)
            {

CummunityInvestmentWeb/Areas/Administrator/Views/AdminActivity/CMSPage.cshtml
@model AdminCmsPageVM
@{
    ViewData["Title"] = Model?.Title != null ? "Edit - "+Model.Title : "Add CMS Page";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@section Styles{
    <script src="https://cdn.tiny.cloud/1/lpumg45i4q2ziehmjw6hy6wouivhb4vr6wypem4t2jm1cc27/tinymce/6/tinymce.min.js" referrerpolicy="origin"></script>
}

@functions {
    public string IsValidField(string Key, ModelStateDictionary modelState)
    {
        return modelState.TryGetValue(Key, out var entry) && entry.Errors.Count > 0 ? "is-invalid" : "";
    }
}

<div class="cms-page-container px-3">
    <div class="cms-page-head px-4 py-3 bg-light border">
        @if (Model?.CmsPageId != null)
        {
            <h4 class="m-0">Edit</h4>
        }
        else
        {
            <h4 class="m-0">Add</h4>
        }
    </div>
    <div class="cms-page-main px-4 py-3 mb-4 border">
        <form id="cms-page-form" asp-action="SaveCMSPage" method="post">
            <input asp-for="CmsPageId" hidden />
            <div class="row g-4">
                <div class="input-container col-12">
                    <label asp-for="Title" class="form-label"></label>
                    <input asp-for="Title" class="form-control input @IsValidField("Title", ViewData.ModelState)" placeholder="Enter Content page title">
                    <span asp-validation-for="Title" class="invalid-feedback"></span>
                </div>
                <div class="input-container col-12">
                    <label asp-for="Description" class="form-label"></label>
                    <textarea asp-for="Description" id="cms-page-description"></textarea>
                </div>
                <div class="input-container col-12">
                    <label asp-for="Slug" class="form-label"></label>
                    <input asp-for="Slug" class="form-control input @IsValidField("Slug", ViewData.ModelState)" placeholder="Enter Slug">
                    <span asp-validation-for="Slug" class="invalid-feedback"></span>
                </div>
                <div class="input-container col-12">
                    <label asp-for="Status" class="form-label"></label>
                    <select asp-for="Status" class="form-select input @IsValidField("Status", ViewData.ModelState)">
                        <option value="1">Active</option>
                        <option value="0">InActive</option>
                    </select>
                    <span asp-validation-for="Status" class="invalid-feedback"></span>
                </div>
            </div>
        </form>
    </div>
    <div class="cms-page-footer text-end">
        <a class="btn secondary-btn cancel-action-btn" asp-area="Administrator" asp-controller="AdminActivity" asp-action="ManageCMSPages">Cancel</a>
        <button type="submit" class="btn primary-btn px-4" id="cmsPage-save-btn" form="cms-page-form">
            <span class="btn-loader spinner-border spinner-border-sm d-none" role="status" aria-hidden="true"></span>
            <span class="btn-content">Save</span>
            <span class="btn-loader d-none">Please wait...</span>
        </button>
    </div>
</div>

@section Scripts{
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.minForCI.js"></script>
    <script src="~/js/AdminActivity/CMSPage.js" asp-append-version="true"></script>
}

CummunityInvestmentWeb/Areas/Administrator/Views/AdminActivity/ManageBanners.cshtml
@{
    ViewData["Title"] = "Manage Banners";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@section Styles{
    <link rel="stylesheet" href=@Url.Content("~/css/AdminActivity/ManageBanners.css") asp-append-version="true" />
}

<div class="cms-container px-3">
    <div class="title-underline-wrapper mb-4">
        <h4 class="title pb-3">Banner Management</h4>
    </div>
    <div class="row mb-4">
        <div class="col-8 col-lg-6">
            <input class="form-control input input-search" id="table-search" placeholder="Search Banner" />
        </div>
        <div class="col-4 col-lg-6 text-end">
            <button class="btn primary-btn" id="admin-add-banner-btn">
                <i class="bi bi-plus-lg rg-icon"></i>
                <span>Add</span>
            </button>
        </div>
    </div>

    <!-- Banner table -->
    <div class="w-100">
        <div class="table-responsive admin-table-wrapper">
            <table class="table table-hover align-middle admin-table w-100 border" id="banner-table">
                <thead class="table-light">
                    <tr>
                        <th scope="col">Title</th>
                        <th scope="col">Sort Order</th>
                        <th scope="col">Last Updated</th>
                        <th scope="col">Action</th>
                    </tr>
                </thead>
                <tbody></tbody>
            </table>
        </div>
    </div>

    <div class="modal fade" id="banner-modal" data-bs-backdrop="static" tabindex="-1" aria-labelledby="bannerModal">
        <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable modal-lg modal-fullscreen-xxl-down" id="admin-banner-modal-dialog">
        </div>
    </div>

    <partial name="_RemoveItemConfirmModal"></partial>
</div>

@section Scripts {
    <script src="~/js/AdminActivity/ManageBanners.js" asp-append-version="true"></script>
}

CummunityInvestmentWeb/Areas/Administrator/Views/AdminActivity/ManageCMSPages.cshtml
@{
    ViewData["Title"] = "CMS Pages";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@section Styles{
    <link rel="stylesheet" href=@Url.Content("~/css/AdminActivity/ManageCMSPages.css") asp-append-version="true" />
}

<div class="cms-container px-3">
    <div class="title-underline-wrapper mb-4">
        <h4 class="title pb-3">CMS Page</h4>
    </div>
    <div class="row mb-4">
        <div class="col-8 col-lg-6">
            <input class="form-control input input-search" id="table-search" placeholder="Search for CMS Page" />
        </div>
        <div class="col-4 col-lg-6 text-end">
            <a class="btn primary-btn" id="admin-add-cmsPage-btn" asp-controller="AdminActivity" asp-action="AddCMSPage">
                <i class="bi bi-plus-lg rg-icon"></i>
                <span>Add</span>
            </a>
        </div>
    </div>

    <!-- CMS Pages table -->
    <div class="w-100">
        <div class="table-responsive admin-table-wrapper">
            <table class="table align-middle admin-table w-100 border" id="cms-pages-table">
                <thead class="table-light">
                    <tr>
                        <th scope="col">Title</th>
                        <th scope="col">Status</th>
                        <th scope="col">Action</th>
                    </tr>
                </thead>
                <tbody></tbody>
            </table>
        </div>
    </div>

    <partial name="_RemoveItemConfirmModal"></partial>
</div>

@section Scripts {
    <script src="~/js/AdminActivity/ManageCMSPages.js" asp-append-version="true"></script>
}

CummunityInvestmentWeb/Areas/Administrator/Views/AdminActivity/ManageUsers.cshtml
@{
    ViewData["Title"] = "Manage Users";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@section Styles{
    <link rel="stylesheet" href=@Url.Content("~/css/AdminActivity/ManageUsers.css") asp-append-version="true" />
}

<div class="users-container px-3">
    <div class="title-underline-wrapper mb-4">
        <h4 class="title pb-3">User</h4>
    </div>
    <div class="row mb-4">
        <div class="col-8 col-lg-6">
            <input class="form-control input input-search" id="table-search" placeholder="Search User" />
        </div>
        <div class="col-4 col-lg-6 text-end">   
            <button type="button" class="btn primary-btn" id="admin-add-user-btn">
                <i class="bi bi-plus-lg rg-icon"></i>
                <span>Add</span>
            </button>
        </div>
    </div>

    <!-- User table -->
    <div class="w-100">
        <div class="table-responsive admin-table-wrapper w-100">
            <table class="table align-middle admin-table w-100 border" id="users-table">
                <thead class="table-light">
                    <tr>
                        <th scope="col">First Name</th>
                        <th scope="col">Last Name</th>
                        <th scope="col">Email</th>
                        <th scope="col">EmployeeId</th>
                        <th scope="col">Department</th>
                        <th scope="col">Status</th>
                        <th scope="col">Action</th>
                    </tr>
                </thead>
                <tbody></tbody>
            </table>
        </div>
    </div>

    <div class="modal fade" id="admin-addOrUpdate-user-modal" data-bs-backdrop="static" tabindex="-1" aria-labelledby="addOrUpdateUser">
        <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable modal-xl modal-fullscreen-xxl-down" id="admin-addOrUpdate-user-modal-dialog">
            
        </div>
    </div>

    <partial name="_RemoveItemConfirmModal"></partial>
</div>

@section Scripts {
    <script src="~/js/AdminActivity/ManageUsers.js" asp-append-version="true"></script>
}